### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by filipbech** [philnash/web-share-wrapper#2]
Nice work guys! 
I was looking through the source and I was noticing that you attach an event-listener (obviously) but never remove it again. 
In a normal SPA-context this would be a memory-problem, but I'm honestly not entirely sure how this works when its a custom-element, and the class-instance itself is actually the DOM-element, and holds both the child with the listener and the callback function (I mean I don't know if the GC can actually collect this?)
However, if for nothing else than teaching cleanup and garbage collection to developers, I would consider cleaning up in the disconnectedCallback.
Im curious if this is just a bug, or if you thought of it already (so I can learn more about the GC)

**Comment by philnash** [comment]
Nope, I had not thought of that. I can only imagine that it's a memory leak, so I will add the disconnectedCallback and remote the listener. Thanks for the feedback!

**Comment by philnash** [comment]
I've added the `disconnectedCallback` with some self clean up right here: https://github.com/philnash/web-share-wrapper/blob/master/src/index.js#L49-L53
