### ISSUE TITLE
Error when "web-share-wrapper" is already defined in CustomElementRegistry

### ISSUE THREAD

**Issue by fdocr** [philnash/web-share-wrapper#5]
Hello 👋 

When using a framework that intercepts navigation links (in our case [InstantClick](http://instantclick.io/)) we're running into a problem with the `web-share-wrapper`. This appears to happen because instead of a full page reload, the optimization from the framework keeps the current page context but just swaps out the page's `<body>` (plus some other details). This causes the `web-share-wrapper` tries to define itself but the custom element already exists in the context.

At [forem/forem](https://github.com/forem/forem) we re-enabled the `web-share-wrapper` (see [this link](https://github.com/forem/forem/issues/9962#issuecomment-704759609) for context) but are now seeing this problem come up in the console:

<img width="810" alt="Screen Shot 2021-06-21 at 17 15 02" src="https://user-images.githubusercontent.com/6045239/122838900-3a5c3600-d2b4-11eb-8bab-af679ba602cc.png">

I tried out a "quick fix" that just checks on `customElements` before defining the custom element. This fixed the issue for us so I'll submit a PR for it in case it's something you would like to include.

**Comment by philnash** [comment]
Oh, interesting. Thanks for raising this, and the associated PR. I'll take a look and try to get this out as quick as I can.

**Comment by philnash** [comment]
Thanks for raising and fixing this. This is merged and released as version 0.2.2.

My guess is that you are using Turbolinks and this JS is loaded within the `<body>`. It might be a good idea for any code that should only be run once, like the defining of web-components, to go in the `<head>`. Even with this fix, the class will get redefined every time it reloads and if there are a number of scripts like this that may affect page interactivity when it needn't do so.
